import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/components/MainLayout";
import { AppContextProvider } from "@/context/Appcontext";

export const metadata: Metadata = {
  title: "luvira jewelry",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>
          <MainLayout>{children}</MainLayout>
        </AppContextProvider>
      </body>
    </html>
  );
}
